name: Build
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.8"

      - name: checkout
        uses: actions/checkout@v2

      - name: build arm64
        run: |
          GOOS=linux GOARCH=arm64 go build -o rbwm
          zip rbwm-arm64.zip rbwm rbwm.service config.json

      - name: build arm
        run: |
          GOOS=linux GOARCH=arm go build -o rbwm
          zip rbwm-arm.zip rbwm rbwm.service config.json

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
